FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

COPY train.py .

RUN pip install --no-cache-dir -r requirements.txt

# Create the models directory with higher permissions
RUN mkdir -p /app/models && chmod 777 /app/models

EXPOSE 8080

CMD ["python", "train.py"]

# build command:
# docker build -t sklearn_train:v1 -f Dockerfile.train .

# run command:
# docker run --rm -p 8080:8080/tcp -v ./app/models:/app/models sklearn_train:v1